# Generated by Django 3.2.7 on 2021-09-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210917_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('objective', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('init_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('school_end_date', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Close'), (1, 'Open')], default=1)),
                ('observations', models.TextField(blank=True, default='S/N', null=True)),
            ],
            options={
                'verbose_name': 'SchoolPeriod',
                'verbose_name_plural': 'SchoolPeriods',
                'db_table': 'school_period',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('objective', models.TextField(blank=True, default='S/N', null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='users.teacher')),
                ('sub_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_coordinator', to='users.teacher')),
                ('teachers', models.ManyToManyField(to='users.Teacher')),
            ],
            options={
                'verbose_name': 'KnowledgeArea',
                'verbose_name_plural': 'KnowledgeAreas',
                'db_table': 'knowledge_area',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('grade_level', models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero')])),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('school_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolperiod')),
                ('students', models.ManyToManyField(blank=True, to='users.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignatureClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('observation', models.TextField(blank=True, null=True)),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.asignature')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asignature',
            name='classrooms',
            field=models.ManyToManyField(blank=True, through='school.AsignatureClassroom', to='school.Classroom'),
        ),
        migrations.AddField(
            model_name='asignature',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.knowledgearea'),
        ),
    ]
