# Generated by Django 3.2.7 on 2021-09-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignature',
            options={'verbose_name': 'Asignature', 'verbose_name_plural': 'Asignatures'},
        ),
        migrations.AlterModelOptions(
            name='asignatureclassroom',
            options={'verbose_name': 'AsignatureClassroom', 'verbose_name_plural': 'AsignaturesClassrooms'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelTable(
            name='asignature',
            table='asignature',
        ),
        migrations.AlterModelTable(
            name='asignatureclassroom',
            table='asignature_classroom',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classroom',
        ),
    ]
