# Generated by Django 3.2.7 on 2021-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210917_1632'),
        ('school', '0002_auto_20210917_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearea',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.Teacher'),
        ),
    ]
