# Generated by Django 3.2.7 on 2021-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_knowledgearea_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='grade_level',
            new_name='curse_level',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
