# Generated by Django 3.2.7 on 2021-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210919_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignature',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
