# Generated by Django 3.2.7 on 2021-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_asignature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignature',
            name='observations',
            field=models.TextField(blank=True, default='S/N', null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='curse_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer')]),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='init_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='school_end_date',
            field=models.DateField(),
        ),
    ]
