# Generated by Django 3.2.7 on 2021-09-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210920_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolperiod',
            name='end_date',
            field=models.DateField(verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='init_date',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='observations',
            field=models.TextField(blank=True, default='S/N', null=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='school_end_date',
            field=models.DateField(verbose_name='fecha fin de clases'),
        ),
        migrations.AlterField(
            model_name='schoolperiod',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1, null=True, verbose_name='estado'),
        ),
    ]
