# Generated by Django 3.2.7 on 2021-09-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210920_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolperiod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
    ]
