# Generated by Django 3.2.7 on 2021-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_knowledgearea_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatureclassroom',
            name='observation',
        ),
        migrations.AddField(
            model_name='asignatureclassroom',
            name='observations',
            field=models.TextField(blank=True, default='S/N', null=True),
        ),
    ]
