# Generated by Django 3.2.7 on 2022-02-11 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abp', '0009_alter_rubricdetailabp_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStepOneAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('moderator_question', models.CharField(max_length=250)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
            ],
            options={
                'verbose_name': 'QuestionStepOneAbp',
                'db_table': 'question_step_one_abp',
            },
        ),
        migrations.CreateModel(
            name='OpinionStepOneAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('opinion', models.TextField()),
                ('active', models.BooleanField(blank=True, default=True)),
                ('team_detail_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamdetailabp')),
            ],
            options={
                'verbose_name': 'OpinionStepOneAbp',
                'db_table': 'opinion_step_one_abp',
            },
        ),
        migrations.CreateModel(
            name='InteractionStepOneAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('opinion_interaction', models.PositiveSmallIntegerField(choices=[(0, 'Nothing'), (1, 'Disagree'), (2, 'Agree')], default=0)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('opinion_step_one_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp_steps.opinionsteponeabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InteractionStepOneAbp',
                'db_table': 'interaction_step_one_abp',
            },
        ),
        migrations.CreateModel(
            name='AnswerStepOneAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('teacher_answer', models.TextField()),
                ('active', models.BooleanField(blank=True, default=True)),
                ('question_step_one_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp_steps.questionsteponeabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnswerStepOneAbp',
                'db_table': 'answer_step_one_abp',
            },
        ),
    ]
