# Generated by Django 3.2.7 on 2022-03-02 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0012_alter_teamabp_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abp_steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownConceptStepFourAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('unknown_concept', models.TextField()),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
            ],
            options={
                'verbose_name': 'UnknownConceptStepFourAbp',
                'db_table': 'unknown_concept_step_four_abp',
            },
        ),
        migrations.CreateModel(
            name='UnknownConceptReferenceStepFourAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('url_reference', models.URLField()),
                ('unknown_concept_step_four_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp_steps.unknownconceptstepfourabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UnknownConceptReferenceStepFourAbp',
                'db_table': 'unknown_concept_reference_step_four_abp',
            },
        ),
        migrations.CreateModel(
            name='StudentIdeaStepTwoAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('student_idea', models.TextField()),
                ('team_detail_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamdetailabp')),
            ],
            options={
                'verbose_name': 'StudentIdeaStepTwoAbp',
                'db_table': 'student_idea_step_one_abp',
            },
        ),
        migrations.CreateModel(
            name='RateStudentIdeaStepTwoAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('rate_student_idea', models.PositiveSmallIntegerField(default=0)),
                ('student_idea_step_two_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp_steps.studentideasteptwoabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RatingStudentIdeaStepTwoAbp',
                'db_table': 'rating_student_idea_step_one_abp',
            },
        ),
        migrations.CreateModel(
            name='ProblemResolutionStepEightAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('problem_resolution', models.TextField()),
                ('video_url', models.URLField()),
                ('image_references', models.JSONField()),
                ('observations', models.TextField()),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
            ],
            options={
                'verbose_name': 'ProblemResolutionStepEightAbp',
                'db_table': 'problem_resolution_step_eight_abp',
            },
        ),
        migrations.CreateModel(
            name='ProblemDefinitionStepSixAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('problem_definition', models.TextField()),
                ('observations', models.TextField()),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
            ],
            options={
                'verbose_name': 'ProblemDefinitionStepSixAbp',
                'db_table': 'problem_definition_step_six_abp',
            },
        ),
        migrations.CreateModel(
            name='PerformActionStepFiveAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('action', models.TextField()),
                ('team_detail_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamdetailabp')),
            ],
            options={
                'verbose_name': 'PerformActionStepFiveAbp',
                'db_table': 'perform_action_step_five_abp',
            },
        ),
        migrations.CreateModel(
            name='LearnedConceptStepThreeAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('learned_concept', models.TextField()),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
            ],
            options={
                'verbose_name': 'LearnedConceptStepThreeAbp',
                'db_table': 'learned_concept_step_three_abp',
            },
        ),
        migrations.CreateModel(
            name='LearnedConceptReferenceStepThreeAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('url_reference', models.URLField()),
                ('learned_concept_step_three_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp_steps.learnedconceptstepthreeabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LearnedConceptReferenceStepThreeAbp',
                'db_table': 'learned_concept_reference_step_three_abp',
            },
        ),
        migrations.CreateModel(
            name='GetInformationStepSevenAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('get_information', models.TextField()),
                ('observations', models.TextField()),
                ('team_detail_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamdetailabp')),
            ],
            options={
                'verbose_name': 'GetInformationStepSevenAbp',
                'db_table': 'get_information_step_seven_abp',
            },
        ),
    ]
