# Generated by Django 3.2.7 on 2022-03-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp_steps', '0003_rateperformactionstepfiveabp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateperformactionstepfiveabp',
            name='rate_perform_action',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
