# Generated by Django 3.2.7 on 2022-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp_steps', '0005_problemdefinitionreferencestepsixabp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdefinitionstepsixabp',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
