# Generated by Django 3.2.7 on 2022-03-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abp', '0012_alter_teamabp_step'),
        ('abp_steps', '0006_alter_problemdefinitionstepsixabp_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationReferenceStepSevenAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('information_reference', models.URLField()),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InformationReferenceStepSevenAbp',
                'db_table': 'information_reference_step_seven_abp',
            },
        ),
    ]
