# Generated by Django 3.2.7 on 2022-03-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0012_alter_teamabp_step'),
        ('abp_steps', '0007_informationreferencestepsevenabp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getinformationstepsevenabp',
            name='team_detail_abp',
        ),
        migrations.AddField(
            model_name='getinformationstepsevenabp',
            name='team_abp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp'),
            preserve_default=False,
        ),
    ]
