# Generated by Django 3.2.7 on 2022-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp_steps', '0008_auto_20220305_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinformationstepsevenabp',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problemresolutionstepeightabp',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
