# Generated by Django 3.2.7 on 2022-01-20 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('problem', models.TextField()),
                ('oral_explication', models.JSONField(blank=True, null=True)),
                ('descriptive_image', models.JSONField(blank=True, null=True)),
                ('reference_url', models.TextField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Close'), (1, 'Open')], default=1)),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
            ],
            options={
                'verbose_name': 'ABP',
                'db_table': 'abp',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('final_grade', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('observation', models.TextField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1)),
                ('abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.abp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EvaluationAbp',
                'verbose_name_plural': 'EvaluationsAbp',
                'db_table': 'evaluation_abp',
            },
        ),
        migrations.CreateModel(
            name='RubricAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('description_rubric', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1, null=True)),
                ('abp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abp.abp')),
            ],
            options={
                'verbose_name': 'RubricAbp',
                'verbose_name_plural': 'RubricsAbp',
                'db_table': 'rubric_abp',
            },
        ),
        migrations.CreateModel(
            name='TeamAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('observations', models.TextField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1, null=True)),
                ('abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.abp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TeamAbp',
                'verbose_name_plural': 'TeamsAbp',
                'db_table': 'team_abp',
            },
        ),
        migrations.CreateModel(
            name='TeamDetailAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('team_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.teamabp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TeamDetailAbp',
                'verbose_name_plural': 'TeamDetailsAbp',
                'db_table': 'team_detail_abp',
            },
        ),
        migrations.CreateModel(
            name='RubricDetailAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('title_detail', models.CharField(max_length=250)),
                ('description_detail', models.TextField(blank=True, null=True)),
                ('grade_percentage', models.CharField(max_length=5)),
                ('rating_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('observations_detail', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('rubric_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.rubricabp')),
            ],
            options={
                'verbose_name': 'RubricDetailAbp',
                'verbose_name_plural': 'RubricDetailsAbp',
                'db_table': 'rubric__detail_abp',
            },
        ),
        migrations.CreateModel(
            name='EvaluationDetailAbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('grade_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('evaluation_description', models.TextField(blank=True, null=True)),
                ('rating_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('evaluation_abp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.evaluationabp')),
            ],
            options={
                'verbose_name': 'EvaluationDetailAbp',
                'verbose_name_plural': 'EvaluationDetailsAbp',
                'db_table': 'evaluation_detail_abp',
            },
        ),
    ]
