# Generated by Django 3.2.7 on 2022-01-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamabp',
            old_name='user',
            new_name='moderator',
        ),
    ]
