# Generated by Django 3.2.7 on 2022-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0002_rename_user_teamabp_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abp',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='rubricabp',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='teamabp',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='teamdetailabp',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
