# Generated by Django 3.2.7 on 2022-01-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0003_auto_20220125_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamabp',
            name='moderator',
        ),
        migrations.AddField(
            model_name='teamdetailabp',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
