# Generated by Django 3.2.7 on 2022-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0005_rubricabp_abp_final_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricdetailabp',
            name='grade_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
