# Generated by Django 3.2.7 on 2022-02-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0007_auto_20220208_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationabp',
            name='final_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationdetailabp',
            name='grade_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationdetailabp',
            name='rating_value',
            field=models.FloatField(default=0),
        ),
    ]
