# Generated by Django 3.2.7 on 2022-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0008_auto_20220208_2310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rubricdetailabp',
            table='rubric_detail_abp',
        ),
    ]
