# Generated by Django 3.2.7 on 2022-02-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0009_alter_rubricdetailabp_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamabp',
            name='step',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Step One'), (2, 'Step Two'), (3, 'Step Three'), (4, 'Step Four'), (5, 'Step Five'), (6, 'Step Six'), (7, 'Step Seven'), (8, 'Step Eight')], default=1, null=True),
        ),
    ]
