# Generated by Django 3.2.7 on 2022-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0012_alter_teamabp_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamabp',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, 'Step One'), (2, 'Step Two'), (3, 'Step Three'), (4, 'Step Four'), (5, 'Step Five'), (6, 'Step Six'), (7, 'Step Seven'), (8, 'Step Eight'), (9, 'Step Nine')], default=1),
        ),
    ]
