# Generated by Django 3.2.7 on 2022-03-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0013_alter_teamabp_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationabp',
            name='user',
        ),
        migrations.AddField(
            model_name='evaluationabp',
            name='team_detail_abp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abp.teamdetailabp'),
            preserve_default=False,
        ),
    ]
