# Generated by Django 3.2.7 on 2022-03-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0014_auto_20220317_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationabp',
            old_name='observation',
            new_name='observations',
        ),
    ]
