# Generated by Django 3.2.7 on 2022-04-27 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac', '0010_alter_teamac_team_state'),
        ('users', '0004_conversation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokesmanQuestionAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('spokesman_question', models.CharField(max_length=255)),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'SpokesmanQuestionAc',
                'verbose_name_plural': 'SpokesmanQuestionsAc',
                'db_table': 'spokesman_question_ac',
            },
        ),
        migrations.CreateModel(
            name='TeacherAnswerAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('teacher_answer', models.TextField()),
                ('spokesman_question_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_roles.spokesmanquestionac')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name': 'TeacherAnswerAc',
                'verbose_name_plural': 'TeacherAnswersAc',
                'db_table': 'teacher_answer_ac',
            },
        ),
        migrations.CreateModel(
            name='TeacherAnswerDescriptionSecretaryAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('teacher_answer_description', models.TextField()),
                ('teacher_answer_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_roles.teacheranswerac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'TeacherAnswerDescriptionSecretaryAc',
                'verbose_name_plural': 'TeacherAnswerDescriptionsSecretaryAc',
                'db_table': 'teacher_answer_description_secretary_ac',
            },
        ),
        migrations.CreateModel(
            name='SecretaryInformationAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('external_path', models.URLField()),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'SecretaryInformationAc',
                'db_table': 'secretary_information_ac',
            },
        ),
        migrations.CreateModel(
            name='ProblemResolutionGroupAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('problem_resolution', models.TextField()),
                ('references_images', models.JSONField(blank=True, default=dict)),
                ('observations', models.TextField()),
                ('team_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamac')),
            ],
            options={
                'verbose_name': 'ProblemResolutionGroupAc',
                'verbose_name_plural': 'ProblemResolutionsGroupAc',
                'db_table': 'problem_resolution_group_ac',
            },
        ),
        migrations.CreateModel(
            name='PerformanceDescriptionSpokesmanAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('performance_description', models.TextField()),
                ('oral_description', models.JSONField(blank=True, default=dict)),
                ('member_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_performance_description_ac', to='ac.teamdetailac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_detail_performance_description_ac', to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'PerformanceDescriptionSpokesmanAc',
                'verbose_name_plural': 'PerformanceDescriptionsSpokesmanAc',
                'db_table': 'performance_description_spokesman_ac',
            },
        ),
        migrations.CreateModel(
            name='OrganizerActionAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('action', models.TextField()),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'OrganizerActionAc',
                'verbose_name_plural': 'OrganizerActionsAc',
                'db_table': 'organizer_action_ac',
            },
        ),
        migrations.CreateModel(
            name='MemberPerformanceCoordinatorAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('member_assessment', models.FloatField()),
                ('member_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_member_performance_ac', to='ac.teamdetailac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_detail_member_performance_ac', to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'MemberPerformanceCoordinatorAc',
                'verbose_name_plural': 'MemberPerformancesCoordinatorAc',
                'db_table': 'member_performance_coordinator_ac',
            },
        ),
        migrations.CreateModel(
            name='FeaturedInformationSecretaryAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('external_path', models.URLField()),
                ('description_path', models.TextField()),
                ('member_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_featured_information_ac', to='ac.teamdetailac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_detail_featured_information_ac', to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'FeaturedInformationSecretaryAc',
                'db_table': 'featured_information_secretary_ac',
            },
        ),
        migrations.CreateModel(
            name='DescribeUnderstandingOrganizerAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('member_assessment', models.IntegerField(default=0)),
                ('understanding', models.TextField()),
                ('member_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_describe_understanding_ac', to='ac.teamdetailac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_detail_describe_understanding_ac', to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'DescribeUnderstandingOrganizerAc',
                'db_table': 'describe_understanding_organizer_ac',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorStrategyAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('strategy', models.TextField()),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'CoordinatorStrategyAc',
                'verbose_name_plural': 'CoordinatorStrategiesAc',
                'db_table': 'coordinator_strategy_ac',
            },
        ),
        migrations.CreateModel(
            name='AssignActivityOrganizerAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('member_activity', models.TextField()),
                ('member_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assign_organizer_ac', to='ac.teamdetailac')),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_detail_assign_organizer_ac', to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'AssignActivityOrganizerAc',
                'verbose_name_plural': 'AssignActivitiesOrganizerAc',
                'db_table': 'assign_activity_organizer_ac',
            },
        ),
        migrations.CreateModel(
            name='ActivityDescriptionSpokesmanAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('activity_description', models.TextField()),
                ('team_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.teamdetailac')),
            ],
            options={
                'verbose_name': 'ActivityDescriptionSpokesmanAc',
                'verbose_name_plural': 'ActivityDescriptionsSpokesmanAc',
                'db_table': 'activity_description_spokesman_ac',
            },
        ),
    ]
