# Generated by Django 3.2.7 on 2022-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_alter_studentevaluationac_evaluation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluationdetailac',
            name='detail_body',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
