# Generated by Django 3.2.7 on 2022-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0003_studentevaluationdetailac_detail_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevaluationac',
            name='evaluation_type',
        ),
        migrations.AddField(
            model_name='studentevaluationdetailac',
            name='evaluation_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Autoevaluation'), (2, 'Coevaluation'), (3, 'Other')], default=3),
            preserve_default=False,
        ),
    ]
