# Generated by Django 3.2.7 on 2022-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0004_auto_20220415_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevaluationac',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
