# Generated by Django 3.2.7 on 2022-04-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0005_alter_studentevaluationac_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEvaluationDetailAc',
        ),
    ]
