# Generated by Django 3.2.7 on 2022-04-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0006_delete_studentevaluationdetailac'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluationDetailAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_state', models.CharField(default='A', max_length=3)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('evaluation_type', models.PositiveSmallIntegerField(choices=[(1, 'Autoevaluation'), (2, 'Coevaluation'), (3, 'Other')])),
                ('detail_value', models.FloatField()),
                ('detail_body', models.JSONField(blank=True, default=dict, null=True)),
                ('rubric_detail_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.rubricdetailac')),
                ('student_evaluation_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.studentevaluationac')),
            ],
            options={
                'verbose_name': 'StudentEvaluationDetailAc',
                'verbose_name_plural': 'StudentEvaluationDetailsAc',
                'db_table': 'student_evaluation_detail_ac',
            },
        ),
    ]
