# Generated by Django 3.2.7 on 2022-04-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0007_studentevaluationdetailac'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamac',
            name='team_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Finished'), (1, 'Working')], default=1),
        ),
    ]
