# Generated by Django 3.2.7 on 2022-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0009_alter_teamac_team_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamac',
            name='team_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Finished'), (1, 'Working')], default=1),
        ),
    ]
